# arrow keys

[DEFAULT]
enabled = true

[PickWalkRight]
keys = right
note = walk rigt

[PickWalkLeft]
keys = left
note = walk left

[PickWalkUp]
keys = up
note = walk up

[PickWalkDown]
keys = down
note = walk down

[MoveRight]
keys = alt+right

[MoveLeft]
keys = alt+left

[MoveDown]
keys = alt+down

[MoveUp]
keys = alt+up
