# camera shortcuts

[DEFAULT]
enabled = true

[CameraModeToggle]
enabled = false
#TODO

[CycleBackgroundColor]
keys = alt+b
note = change viewport collor

[FrameSelectedWithoutChildren]
keys = u
note = reframe selected

[FrameSelectedInAllViews]
keys = alt+u
note = reframe in all views with all of the childs

[FrameSelectedWithoutChildrenInAllViews]
keys = ctrl+u
note = reframe in all views without the children

[DisplayWireframe]
keys = 3
note = display wireframe, disabled because better script
enabled = false

[ToggleWireframeOnShadedCmd]
keys = 3
note = use better script
enabled = false

[mk_ToggleWireframe]
keys = f2
note = wireframe <> wireframe on shaded
script = scripts/toggle_wireframe.py

[DisplayShaded]
keys = 4
note = use script
enabled = false

[DisplayShadedAndTextured]
keys = 4
note = use better script
enabled = false

[DisplayLight]
keys = 4
note = use script damit its redundant
enabled = false

[mk_CycleShading]
keys = f3
note = shaded > textured > textured+lights; from wireframe go to textured
script = scripts/cycle_shading.py

[CreateCameraFromView]
enabled = false
note = creata camera from viewport positiion
#TODO(Katie): bind
