# sequencer

[DEFAULT]
enabled = true
context = sequenceEditorPanel

[SequencerFrameSelected]
keys = u
note = reframe current selection, same key as GlobalReframe

[SequencerToggleHoldMode]
keys = y
note = hold mode
