# motionmaker context

[DEFAULT]
enabled = true
context = motionMakerEditor

[MotionMakerEditorPinSelectedCharacter]
keys = 5
note = pin current character, same binding as Parent

[MotionMakerEditorFrameSelection]
keys = u
note = refarame to selection, same key as GlobalReframe
