# maya node editor

[DEFAULT]
enabled = true
context = nodeEditorPanel

[NodeEditorToggleNodeSelectedPins]
key = 5
note = toggle current selection, same binding as Parent

[NodeEditorShowCustomAttrs]
enabled = false
#TODO

[NodeEditorToggleNodeTitleMode]
enabled = false
#TODO
