# time editor

[DEFAULT]
enabled = true
context = timeEditorPanel

[TimeEditorCreatePoseClip]
keys = 5
note = create pose clip from the current selection, same binding as Parent

[TimeEditorFrameSelected]
keys = u
note = reframe to the current selection, same key as GlobalReframe

[TimeEditorSetZeroKey]
enabled = false
#TODO

[TimeEditorClipHoldToggle]
keys = y
note = hold edit mode
