# hypershade editor

[DEFAULT]
enabled = true
context = hyperShadePanel

[HypershadePinSelected]
keys = 5
note = Pin current selection, same binding as Parent

[HypershadeShowCustomAttrs]
enabled = false

[HypershadeToggleNodeTitleMode]
enabled = false
