# sequencer

[DEFAULT]
enabled = true
context = sequenceEditorPanel

[SequencerFrameSelected]
keys = u
note = reframe current selection, same key as GlobalReframe

[SequencerToggleHoldMode]
keys = y
note = hold mode

[SequencerCopyShots]
keys = ctrl+c
note = same bind as CopySelected

[SequencerPasteShots]
keys = ctrl+.
note = same bind as PasteSelected

[SequencerNextShot]
keys = right

[SequencerPrevShot]
keys = left

[SequencerIncreaseTrackHeight]
keys = up

[SequencerDecreaseTrackHeight]
keys = down
