# outliner panel

[DEFAULT]
enabled = true
context = 

[OutlinerRevealSelected]
keys = u
enabled = false
note = expand on the current selection, same key as GlobalReframe for now, should change ?
#TODO
