# shapePanel

[DEFAULT]
context = shapePanel
enabled = true

[ShapeEditorDuplicateTarget]
keys = ctrl+,
note = same bind as Duplicate

[ShapeEditorSelectNone]
enabled = false
#TODO

[ShapeEditorNewGroup]
keys = ctrl+q
note = same bind as Group
