# sculpt tool context

[DEFAULT]
enabled = true
context = sculptMeshCache

[SculptMeshFrame]
keys = u
note = reframe the current mesh, same key as GlobalReframe

[SetMeshSculptTool]
enabled = false

[SetMeshSmoothTool]
enabled = false

[SetMeshRelaxTool]
enabled = false

[SetMeshGrabTool]
enabled = false

[SetMeshPinchTool]
enabled = false

[SetMeshFlattenTool]
enabled = false

[SetMeshFoamyTool]
enabled = false

[SetMeshSprayTool]
enabled = false

[SetMeshRepeatTool]
enabled = false

[SetMeshFreezeTool]
enabled = false
