# time editor

[DEFAULT]
enabled = true
context = timeEditorPanel

[TimeEditorCreatePoseClip]
keys = 5
note = create pose clip from the current selection, same binding as Parent

[TimeEditorFrameSelected]
keys = u
note = reframe to the current selection, same key as GlobalReframe

[TimeEditorSetZeroKey]
enabled = false
#TODO

[TimeEditorClipHoldToggle]
keys = y
note = hold edit mode

[TimeEditorCopyClips]
keys = ctrl+c
note = same bind as CopySelected

[TimeEditorPasteClips]
keys = ctrl+.
note = same bind as PasteSelected

[TimeEditorCreateGroupFromSelection]
keys = ctrl+q
note = same bind as Group

[TimeEditorExportSelection]
keys = ctrl+o
note = same bind as ExportSelection

[TimeEditorCutClips]
keys = ctrl+'
note = same bind as CutSelected
