# dope sheet context

[DEFAULT]
enabled = true
context = dopeSheetPanel

[DopeSheetUnlockChannel]
keys = ,
note = unlock channel in dope sheet, same key as snapping toggle

[DopeSheetFrameSelected]
keys = u
note = refarme to selection, same key as GlobalReframe
