# uv tool shortcuts, most of this is in the uv context

[DEFAULT]
enabled = true
context = polyTexturePlacementPanel

[MoveUVTool]
keys = i
note = move in the UV editor

[RotateUVTool]
keys = a
note = rotate in the UV tool

[ScaleUVTool]
keys = e
note = scale in the uv tool, same as GlobalScale

[UVEditorFrameSelected]
keys = u
note = reframe current selection, same key as GlobalReframe

[DisplayUVWireframe]
keys = 3
note = Show wireframe of the uv, same as DisplayWireframe

[DisplayUVShaded]
enabled = false
#TODO: URGENT

[ToggleUVTextureImage]
enabled = false
#TODO: URGENT

[ToggleUVDistortion]
enabled = false
#TODO: URGENT
