# maya graph editor

[DEFAULT]
enabled = true
context = graphEditor

[GraphEditorUnlockChannel]
keys = ,
note = graph editor unlock the channel, same key as snapping toggle

[GraphEditorFrameSelected]
keys = u
note = grapdh editor reframe, same key as GlobalReframe
