# ngskintools

[DEFAULT]
enabled = true
context = ngst2PaintContext

[SkinToolsViewFitInfluence]
keys = u
note = reframe the current influences in the view, same key as GlobalReframe

[SkinToolsPaintFlood]
keys = ctrl+u
enabled = false
note = flood the area, same key as GlobalReframe
#TODO: remap to something that makes more sense ?

[SkinToolsCycleWeightsDisplayMode]
keys = b
note = change display mode
