# copy operations

[DEFAULT]
enabled = true

[Duplicate]
keys = ctrl+,
note = duplicate current selection

[DuplicateSpecial]
keys = ctrl+shift+,
note = duplicate special for current selection

[DuplicateWithTransform]
keys = alt+shift+,
note = duplicate the current selection while keeping the current transform

[CopySelected]
keys = ctrl+c
note = copy current selection

[PasteSelected]
keys = ctrl+.
note = paste clipboard content

[CutSelected]
keys = ctrl+'
note = cut current selection
