# file operations

[SaveScene]
keys = ctrl+a
note = serialise scene to save point

[SaveSceneAs]
keys = alt+o
note = serialise scene to new file

[IncrementAndSave]
keys = alt+a
note = serialise scene to the next increment file

[ExportSelection]
keys = ctrl+o
note = export selection (why is this not a shortcut in stock lmao)

[Export]
keys = ctrl+shift+o
note = export entier scene

[OpenScene]
keys = ctrl+4
note = show opes scene dialogue
