# global snapping settings

[DEFAULT]
enabled = true

[dR_pointSnap]
keys = '
note = Vertex snapping to verticies, press bind
command = dR_pointSnapPress
release = dR_pointSnapRelease

[mk_CycleAxis]
keys = .
note = cycle active transform tool axis: object > world > component
script = scripts/cycle_axis.py

[WorldMoveRotateScaleToolToggleSnap]
keys = ,
note = toggle the tool specific snapping for in world coordonets
command = MoveRotateScaleToolToggleSnapMode
release = MoveRotateScaleToolToggleSnapMode

[LocalMoveRotateScaleToolToggleSnap]
keys = alt+,
note = toggle the tool specific snapping for local coordonets
command = MoveRotateScaleToolToggleSnapRelativeMode
release = MoveRotateScaleToolToggleSnapRelativeMode
