# global state of maya and its viewport, selecton modes and stuff

[DEFAULT]
enable = true

[RepeatLast]
keys = b
note = Repeat last acction

[NonSacredTool]
keys = y
note = last tool context

[GlobalShowManip]
keys = shift+y
command = ShowManipulators
note = show manipulator for the tool that was used
