# all of the hide/isolate shortcuts

[DEFAULT]
enabled = true

[ToggleVisibilityAndKeepSelection]
keys = -
note = hides or unhides the current selection

[ShowLastHidden]
keys = =
note = unhides previous hiding operation

[mk_ShowPanel]
keys = alt+-
script = scripts/viewport_toggles.py
note = show panel to see what in the viewport is shown or not
