# all of the hide/isolate shortcuts

[DEFAULT]
enabled = true

[ToggleVisibilityAndKeepSelection]
keys = -
note = hides or unhides the current selection

[ShowLastHidden]
keys = =
note = unhides previous hiding operation


