# selection tools

[DEFAULT]
enabled = true

[SelectNone]
enabled = false
#TODO

[SelectToggleMode]
keys = 4
note = select objects

[SelectFacetMask]
keys = 3
note = select faces

[ConvertSelectionToFaces]
keys = ctrl+3

[SelectVertexMask]
keys = 2
note = select verticies

[ConvertSelectionToVertices]
keys = ctrl+2

[SelectVertexFaceMask]
keys = alt+2

[SelectUVMask]
keys = alt+f5
note = select uv mask

[SelectMeshUVShell]
keys = f5
note = select uv shell

[ConvertSelectionToUVs]
keys = ctrl+f5

[SelectEdgeMask]
keys = f4
note = select edges

[ConvertSelectionToEdges]
keys = ctrl+f4

[SoftSelect]
keys = \
command = dR_softSelStickyPress
release = dR_softSelStickyRelease

[SelectTool]
keys = ctrl+/
note = box selection tool

[LassoTool]
keys = /
note = lasso main selection tool ^^

#[ArtPaintSelectTool]
#keys = alt+/

[dR_paintPress]
keys = f1
note = selection paint tool, used to be tab
commnand = dR_paintPress
release = dR_paintRelease
