# transform tools shortcuts

[DEFAULT]
enabled = true

[GlobalTranslate]
keys = i
note = move tool
command = TranslateToolWithSnapMarkingMenu
release = TranslateToolWithSnapMarkingMenuPopDown

[EditMode]
keys = c
note = transform edit mode for editing the pivot and moving it around
command = EnterEditModePress
release = EnterEditModeRelease

[GlobalRotate]
keys = a
note = rotate tool
command = RotateToolWithSnapMarkingMenu
release = RotateToolWithSnapMarkingMenuPopDown

[GlobalScale]
keys = e
note = scale tool
command = ScaleToolWithSnapMarkingMenu
release = ScaleToolWithSnapMarkingMenuPopDown
